import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google";

import "./globals.css";

import headerImg from "../assets/desktop/bg-pattern-header.svg";
import Header from "./components/Header/Header";

const kumbhSans = Kumbh_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={kumbhSans.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
